---
- name: Gather and Display Cisco Device Information
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather facts from Cisco devices
      ios_facts:
        gather_subset:
          - config
          - default
          - hardware

    - name: Generate HTML table
      set_fact:
        html_table: |
          <table border="1">
          <tr><th>Attribute</th><th>Value</th></tr>
          <tr><td>Hostname</td><td>{{ ansible_net_hostname }}</td></tr>
          <tr><td>Model</td><td>{{ ansible_net_model }}</td></tr>
          <!-- ... (other attributes) ... -->
          </table>

    - name: Display generated HTML table
      debug:
        var: html_table

    - name: Save HTML content to FTP server
      uri:
        url: "ftp://cisco:cisco123@10.1.196.117/output.html"
        method: PUT
        body: "{{ ansible_facts.html_table }}"
        force_basic_auth: yes
      delegate_to: localhost
