---
- name: 2960 Upgrade
  hosts: all
  gather_facts: no
  vars:
    new_version: 17.09.03
    new_file: "cat9k_lite_iosxe.{{ new_version }}.SPA.bin"

  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output
    
    - name: print output
      debug:
        msg: "Current Version is {{ facts_output['ansible_facts']['ansible_net_version'] }}"
    
    - name: Save the Config
      cisco.ios.ios_command:
        commands: 
          - command: 'copy running-config startup-config'
            prompt: 'Destination filename \[startup-config\]\?'
            answer: "\r"
      register: save_config
    
    - name: Save config output
      debug:
        msg: "{{ save_config }}"
    
    
          
      - name: Copy IOS image via FTP
        cisco.ios.ios_command:
          commands:
            - command: "copy ftp://cisco:cisco123@10.1.196.117/{{ new_file }}  flash:{{ new_file }}   vrf Mgmt-vrf"
              prompt:
                - 'Destination filename [{{ new_file }} ]?'
              answer:
                - "\r"
        vars:
          ansible_command_timeout: 900

## Change the Boot Variable to the new image 

   - name: Change Boot Variable to new image 
     ios_config: 
       commands: 
         - "boot system flash:{{ new_file }}"
       save_when: always 

## Reload the device 

   - name: Reload the Device 
     cli_command: 
       command: reload
       prompt: 
         - confirm
       answer: 
         - 'y'
         
- name: Wait for switch to reboot and become reachable
        wait_for_connection:
          delay: 180
          sleep: 60
          timeout: 900
      
      - name: Gather new facts
        cisco.ios.ios_facts:
          gather_subset: hardware
        register: facts_output_new
      
      - name: New Version
        debug:
          msg: "New Version is {{ facts_output_new['ansible_facts']['ansible_net_version'] }}, Upgrade Successfully Completed"
        when: new_version == facts_output_new['ansible_facts']['ansible_net_version']
      
      when: new_version != facts_output['ansible_facts']['ansible_net_version']

       
 
