---
- name: Upgrade Cisco Catalyst Switches IOS XE
  hosts: cisco_devices
  gather_facts: no
  connection: network_cli

  vars:
    new_ios_image: "cat9k_lite_iosxe.17.09.03.SPA.bin"  # The name of the new IOS XE image file.

  tasks:
    - name: Copy IOS XE Image via TFTP
      ios_command:
        commands:
          - "copy tftp: flash:"
          - "10.1.196.117"
          - "{{ new_ios_image }}"

    - name: Set Boot System
      ios_command:
        commands:
          - "config terminal"
          - "boot system flash:{{ new_ios_image }}"
          - "end"

    - name: Upgrade IOS XE Image
      ios_command:
        commands:
          - "install add file flash:{{ new_ios_image }} activate commit"
          - "send n"
      ignore_errors: true

    - name: Wait for Upgrade to Complete
      pause:
        seconds: 660
      # Adjust the duration if necessary based on actual upgrade time

    - name: Save Configuration
      ios_command:
        commands:
          - "write memory"

    - name: Reload Switches
      ios_command:
        commands:
          - "reload in 5"
      async: 600
      poll: 0

    - name: Wait for Switches to Restart
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 900
      delegate_to: localhost

    - name: Verify Upgraded IOS XE Version
      ios_command:
        commands:
          - "show version"
      register: upgraded_version

    - name: Print Upgraded Version Information
      ansible.builtin.debug:
        var: upgraded_version.stdout_lines
