---
- name: Upgrade IOS XE 
  hosts: all
  gather_facts: no

  tasks:

  - name: Remove inactive packages
    ios_config:
      lines:
        - install remove inactive

  - name: Copy new image via TFTP
    ios_copy:
      src: 10.1.196.117/cat9k_iosxe.17.09.03.SPA.bin
      dest: flash:cat9k_iosxe.17.09.03.SPA.bin
      protocol: tftp

  - name: Set boot variable
    ios_system:
      set_bootvar: flash:packages.conf

  - name: Activate new image 
    ios_config:
      lines:
        - install add flash:cat9k_iosxe.17.09.03.SPA.bin activate commit

  - name: Wait for switch to reload
    wait_for_connection:
      timeout: 600

- name: Verify upgrade
  gather_facts: no
  tasks:

  - name: Check new IOS XE version
    ios_command: 
      commands:
        - show version
    register: output

  - debug:
      msg: "Upgraded to {{ output.stdout[0] }}"
