---
- name: Upgrade Cisco Catalyst 9200 Switch
  hosts: switches
  gather_facts: no
  tasks:
    - name: Copy IOS Image via TFTP
      ios_command:
        commands:
          - copy tftp: flash:
          - 10.1.196.117
          - cat9k_lite_iosxe.17.09.03.SPA.bin

    - name: Set Boot System
      ios_command:
        commands:
          - config terminal
          - boot system flash:packages.conf
          - end

    - name: Install and Activate IOS Image
      ios_command:
        commands:
          - install add file flash:cat9k_lite_iosxe.17.09.03.SPA.bin activate commit

    - name: Save Configuration Changes
      ios_command:
        commands:
          - write memory

    - name: Reload Switch for Upgrade
      ios_command:
        commands:
          - reload
      async: 600
      poll: 0

    - name: Wait for Switch to Restart
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 300
      delegate_to: localhost

    - name: Verify Switch Connectivity
      wait_for_connection:
        timeout: 300

    - name: Verify Switch After Upgrade
      ios_command:
        commands:
          - show version
      register: upgraded_version

    - name: Print Upgraded Version Information
      debug:
        var: upgraded_version.stdout_lines
