---
- hosts: cisco_switches
  gather_facts: no

  vars:
    old_version: 17.08.01 
    new_version: 17.09.03
    new_ios_image: cat9k_lite_iosxe.17.09.03.SPA.bin

  tasks:

  - name: Check current IOS version
    ios_command:
      commands: show version
    register: version_output

  - name: Copy new IOS image to flash
    copy:
      src: "{{ new_ios_image }}"
      dest: flash0:/

    - name: Set boot variable to new image
      ios_system:
        set_bootvar: "{{ new_ios_image }}"
      when: "{{ old_version }} in version_output.stdout[0]"

    - name: Reload switch for upgrade
      ios_command: 
        commands: reload
      when: "{{ old_version }} in version_output.stdout[0]"
    
    - name: Wait for device to reload
      wait_for_connection:
        delay: 120 
        sleep: 30
        timeout: 300

    - name: Verify upgraded version
      ios_command: 
        commands: show version
      register: new_version

    - debug:
        msg: "IOS upgraded from {{ old_version }} to {{ new_version.stdout[0] }}"
