---
- name: Gather Cisco device information and Upgrade IOS XE
  hosts: cisco_devices
  gather_facts: no  # We don't need to gather facts from the controller node

  tasks:
    - name: Get Cisco IOS Facts
      ios_facts:
        gather_subset: hardware
      register: cisco_facts

    - name: Copy IOS Image via TFTP
      ios_command:
        commands:
          - "copy tftp: flash:"
          - "10.252.8.103"
          - "cat9k_lite_iosxe.17.09.03.SPA.bin"

    - name: Set Boot System
      ios_command:
        commands:
          - "config terminal"
          - "boot system flash:packages.conf"
          - "end"

    - name: Upgrade IOS XE Image
      ios_command:
        commands:
          - "install add file flash:cat9k_lite_iosxe.17.09.03.SPA.bin activate commit"
          - "send n"
      ignore_errors: true

    - name: Wait for Upgrade to Complete
      pause:
        seconds: 660
      # Adjust the duration if necessary based on actual upgrade time

    - name: Save Configuration
      ios_command:
        commands:
          - "write memory"

    - name: Reload Switches
      ios_command:
        commands:
          - "reload in 5"
      async: 600
      poll: 0

    - name: Wait for Switches to Restart
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 10
        timeout: 900
      delegate_to: localhost

    - name: Verify Switches After Upgrade
      ios_command:
        commands:
          - "show version"
      register: upgraded_version

    - name: Print Upgraded Version Information
      debug:
        var: upgraded_version.stdout_lines
