---
- name: Upgrade IOS XE
  hosts: all
  gather_facts: no

  vars:
    tftp_server: 10.1.196.117
    new_image: cat9k_lite_iosxe.17.09.03.SPA.bin

  tasks:

  - name: Copy new image via TFTP
    ios_copy:
      src: "{{ tftp_server }}/{{ new_image }}"
      dest: "{{ new_image }}"
      protocol: tftp

  - name: Set boot variable
    ios_system:
      set_bootvar: flash:packages.conf

  - name: Activate new image
    ios_config:
      lines:
        - install add flash:{{ new_image }} activate commit

  - name: Wait for switch to reload
    wait_for_connection:
      timeout: 600

  - name: Check new version
    ios_command:
      commands:
        - show version
    register: output
  
  - debug:
      msg: "Upgraded IOS XE to {{ output.stdout[0] }}"
