---
- name: Check IOS XE version
  hosts: cisco_switches
  gather_facts: no

  tasks:

  - name: Get current version
    ios_command:
      commands:
        - show version
    register: version_output

- name: Upgrade IOS XE
  hosts: cisco_switches
  gather_facts: no

  vars:
    - tftp_server: 10.1.196.117
    - new_image: cat9k_lite_iosxe.17.09.03.SPA.bin

  tasks:

  - name: Remove inactive package
    ios_config:
      lines:
        - install remove inactive

  - name: Copy new image via TFTP 
    copy:
      src: "{{ new_image }}"
      dest: flash:
      host: "{{ tftp_server }}"

  - name: Set boot variable
    ios_system:
      set_bootvar: flash:packages.conf

  - name: Activate new image
    ios_config:
      lines:
        - install add flash:{{ new_image }} activate commit
  
  - name: Wait for switch to reload
    wait_for_connection:
      delay: 120
      timeout: 600
      
  - name: Check new version
    ios_command:
      commands:
        - show version
    register: new_version_output

  - debug:
      msg: "{{ new_version_output.stdout_lines[0] }}"
