- hosts: cisco_switches
  
  vars:
    old_version: 17.08.01
    new_version: 17.09.03
    tftp_server: 10.1.196.117
    new_ios_image: cat9k_lite_iosxe.17.09.03.SPA.bin

  tasks:

  - name: Copy new IOS image from TFTP 
    copy:
      src: "{{ new_ios_image }}"
      dest: flash0:/
      host: "{{ tftp_server }}"

    - name: Set boot variable
      ios_system:
        set_bootvar: "{{ new_ios_image }}"
      when: "{{ old_version }} in {{ inventory_hostname }}"

    - name: Reload switch
      ios_command:
        commands: 
          - reload
    
    - name: Wait for reload
      wait_for_connection:
        delay: 120
        sleep: 30  

    - name: Check new version
      ios_command: 
        commands: 
          - show version
      register: output

    - debug:
        msg: "IOS upgraded from {{ old_version }} to {{ output.stdout[0] }}"
