---
- name: Gather Cisco Device Facts
  hosts: cisco_devices
  gather_facts: no
  tasks:
    - name: Collect Cisco device facts
      ios_facts:
        gather_subset: hardware
      register: cisco_facts

    - name: Create HTML content
      set_fact:
        html_content: |
          <table border="1">
          <tr><th>Attribute</th><th>Value</th></tr>
          {% for key, value in cisco_facts.ansible_facts.items() %}
          <tr><td>{{ key }}</td><td>{{ value }}</td></tr>
          {% endfor %}
          </table>

    - name: Create temporary HTML file
      tempfile:
        suffix: '.html'
      register: temp_html_file

    - name: Write HTML content to temporary file
      copy:
        dest: "{{ temp_html_file.path }}"
        content: "{{ html_content }}"

    - name: Upload HTML file to FTP server
      uri:
        url: "ftp://cisco:cisco123@10.1.196.117/report/{{ temp_html_file.path | basename }}"
        method: PUT
        src: "{{ temp_html_file.path }}"
      delegate_to: localhost
