---
- name: Gather and Display Cisco Device Information
  hosts: cisco_devices
  gather_facts: no

  tasks:
    - name: Gather facts from Cisco devices
      ios_facts:
        gather_subset:
          - config
          - default
          - hardware

    - name: Generate CSV content
      set_fact:
        csv_content: |
          Attribute,Value
          Hostname,{{ ansible_net_hostname }}
          Model,{{ ansible_net_model }}
          Serial Number,{{ ansible_net_serialnum }}
          IOS Version,{{ ansible_net_version }}
          Total Memory,{{ ansible_net_memtotal_mb }} MB
          Free Memory,{{ ansible_net_memfree_mb }} MB
          Image,{{ ansible_net_image }}
          IOStype,{{ ansible_net_iostype }}
          Operating Mode,{{ ansible_net_operatingmode }}
          Python Version,{{ ansible_net_python_version }}
          Stacked Models,{{ ansible_net_stacked_models | join(', ') }}
          Stacked Serials,{{ ansible_net_stacked_serialnums | join(', ') }}
          System,{{ ansible_net_system }}
          Virtual Switch,{{ ansible_net_virtual_switch }}

    - name: Display generated CSV content
      debug:
        var: csv_content

    - name: Save CSV content to local file
      copy:
        content: "{{ csv_content }}"
        dest: "/tmp/cisco_info.csv"

    - name: Upload CSV file to FTP server
      uri:
        url: "ftp://cisco:cisco123@10.1.196.117/cisco_info.csv"
        method: PUT
        body: "{{ lookup('file', '/tmp/cisco_info.csv') }}"
        force_basic_auth: yes
      delegate_to: localhost
