---
- name: Gather and Upload Cisco Device Information
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather facts from Cisco devices
      ios_facts:
        gather_subset:
          - config
          - default
          - hardware

    - name: Generate report content
      set_fact:
        report_content: |
          Hostname:          {{ ansible_net_hostname }}
          Model:             {{ ansible_net_model }}
          Serial Number:     {{ ansible_net_serialnum }}
          IOS Version:       {{ ansible_net_version }}
          Total Memory:      {{ ansible_net_memtotal_mb }} MB
          Free Memory:       {{ ansible_net_memfree_mb }} MB
          Image:             {{ ansible_net_image }}
          IOStype:           {{ ansible_net_iostype }}
          Operating Mode:    {{ ansible_net_operatingmode }}
          Python Version:    {{ ansible_net_python_version }}
          Stacked Models:    {{ ansible_net_stacked_models | join(', ') }}
          Stacked Serials:   {{ ansible_net_stacked_serialnums | join(', ') }}
          System:            {{ ansible_net_system }}
          Virtual Switch:    {{ ansible_net_virtual_switch }}

    - name: Upload report content to FTP server
      ansible.builtin.shell: >
        echo "{{ report_content }}" | ftp -n 10.1.196.117 <<END_SCRIPT
        quote USER cisco
        quote PASS cisco123
        put - /report/{{ ansible_net_hostname }}_report.txt
        quit
        END_SCRIPT
      delegate_to: localhost
