---
- name: Gather Cisco Device Information and Upload Report
  hosts: all
  gather_facts: yes
  tasks:
    - name: Gather Cisco Device Facts
      cisco_ios_command:
        commands:
          - show version
          - show inventory
          - show processes cpu history
      register: device_info

    - name: Create report content
      set_fact:
        report_content: |
          Hostname: {{ ansible_net_hostname }}
          Model: {{ ansible_net_model }}
          Serial Number: {{ ansible_net_serialnum }}
          IOS Version: {{ ansible_net_version }}
          Total Memory: {{ ansible_net_memtotal_mb }} MB
          Free Memory: {{ ansible_net_memfree_mb }} MB
          Image: {{ ansible_net_image }}
          IOStype: {{ ansible_net_iostype }}
          Operating Mode: {{ ansible_net_operatingmode }}
          Python Version: {{ ansible_net_python_version }}
          Stacked Models: {{ ansible_net_stacked_models | join(', ') }}
          Stacked Serial Numbers: {{ ansible_net_stacked_serialnums | join(', ') }}
          System: {{ ansible_net_system }}
          Virtual Switch: {{ ansible_net_virtual_switch }}

    - name: Upload report content to FTP server
      community.general.uri:
        url: "ftp://cisco:cisco123@10.1.196.117/report/{{ ansible_net_hostname }}.txt"
        method: PUT
        body: "{{ report_content }}"
        return_content: yes
      delegate_to: localhost
