---
- name: Gather and Upload Cisco Device Information
  hosts: all
  gather_facts: no
  tasks:
    - name: Gather facts from Cisco device
      ios_facts:
        gather_subset: all
      register: device_facts

    - name: Write facts to a temporary file on target host
      copy:
        content: "{{ device_facts | to_nice_json }}"
        dest: "/tmp/{{ inventory_hostname }}_facts.json"

    - name: Upload facts to FTP Server
      expect:
        command: "ftp -n 10.1.196.117"
        responses:
          "(?i)Name .*:": "cisco"
          "(?i)Password .*:": "cisco123"
          "(?i)ftp>": "put /tmp/{{ inventory_hostname }}_facts.json"
