---
- name: Gather Cisco Device Information
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather facts from Cisco devices
      ios_facts:
        gather_subset:
          - hardware
          - config
      register: cisco_facts

    - name: Print Cisco device information
      debug:
        var: cisco_facts
