---
- name: Gather and Display Cisco Device Information
  hosts: all
  gather_facts: no

  tasks:
    - name: Gather facts from Cisco devices
      ios_facts:
        gather_subset:
          - config
          - default
          - hardware

    - name: Generate HTML table
      set_fact:
        html_table: |
          <table border="1">
          <tr><th>Attribute</th><th>Value</th></tr>
          <tr><td>Hostname</td><td>{{ ansible_net_hostname }}</td></tr>
          <tr><td>Model</td><td>{{ ansible_net_model }}</td></tr>
          <tr><td>Serial Number</td><td>{{ ansible_net_serialnum }}</td></tr>
          <tr><td>IOS Version</td><td>{{ ansible_net_version }}</td></tr>
          <tr><td>Total Memory</td><td>{{ ansible_net_memtotal_mb }} MB</td></tr>
          <tr><td>Free Memory</td><td>{{ ansible_net_memfree_mb }} MB</td></tr>
          <tr><td>Image</td><td>{{ ansible_net_image }}</td></tr>
          <tr><td>IOStype</td><td>{{ ansible_net_iostype }}</td></tr>
          <tr><td>Operating Mode</td><td>{{ ansible_net_operatingmode }}</td></tr>
          <tr><td>Python Version</td><td>{{ ansible_net_python_version }}</td></tr>
          <tr><td>Stacked Models</td><td>{{ ansible_net_stacked_models | join(', ') }}</td></tr>
          <tr><td>Stacked Serials</td><td>{{ ansible_net_stacked_serialnums | join(', ') }}</td></tr>
          <tr><td>System</td><td>{{ ansible_net_system }}</td></tr>
          <tr><td>Virtual Switch</td><td>{{ ansible_net_virtual_switch }}</td></tr>
          </table>
