---
- name: Copy IOS Image via TFTP
  hosts: all
  gather_facts: no
  vars:
    tftp_server: "10.1.196.117"
    new_image: "cat9k_lite_iosxe.17.09.03.SPA.bin"
    new_file: "cat9k_lite_iosxe.17.09.03.SPA.bin"

  tasks:
    - name: Copy IOS image via TFTP
      cisco.ios.ios_command_string:
        commands: "copy tftp://{{ tftp_server }}/{{ new_image }} flash:/{{ new_file }}\r\n"
        wait_for: "Destination filename [{{ new_file }}]?"
      register: copy_output
      vars:
        ansible_command_timeout: 120

    - name: Display copy output
      debug:
        var: copy_output.stdout_lines
