---
- name: Copy IOS Image via TFTP
  hosts: all
  gather_facts: no
  vars:
    tftp_server: "10.1.196.117"
    image_filename: "cat9k_lite_iosxe.17.09.03.SPA.bin"

  tasks:
    - name: Copy new image via TFTP
  ios_command:
    commands:

      - command: copy tftp://10.1.196.117/cat9k_lite_iosxe.17.09.03.SPA.bin flash:/cat9k_lite_iosxe.17.09.03.SPA.bin
        sendonly: true

      - command: ''
        sendonly: true
        
      - command: ''
        sendonly: true

    - name: Display copy output
      debug:
        var: copy_output.stdout_lines
