---
- name: Copy IOS XE image to switch
  hosts: switches  # Specify the target hosts here
  gather_facts: no
  vars:
    tftp_server: 10.1.196.117  # TFTP server IP address
    ios_image_filename: cat9k_lite_iosxe.17.09.03.SPA.bin  # The name of the IOS XE image file

  tasks:
    - name: Copy IOS XE image via TFTP
      ios_command:
        commands:
          - "copy tftp://{{ tftp_server }}/{{ ios_image_filename }} flash:/{{ ios_image_filename }}"
      register: copy_result
      ignore_errors: yes

    - name: Print copy result
      debug:
        var: copy_result.stdout_lines
