- name: Copy IOS XE Image via TFTP
  hosts: all
  gather_facts: no

  tasks:
    # ... (other tasks)

    - name: Copy IOS image via FTP
      cisco.ios.ios_command:
        commands:
          - command: "copy ftp://cisco:cisco123@10.1.196.117/cat9k_lite_iosxe.17.09.03.SPA.bin flash:cat9k_lite_iosxe.17.09.03.SPA.bin  vrf Mgmt-vrf"
            prompt:
              - 'Destination filename [cat9k_lite_iosxe.17.09.03.SPA.bin]?'
            answer:
              - "\r"
      vars:
        ansible_command_timeout: 900

 
