---
- name: Copy and Upgrade IOS XE Image
  hosts: all
  gather_facts: no

  vars:
    tftp_server: "10.1.196.117"
    new_file: "cat9k_lite_iosxe.17.09.03.SPA.bin"

  tasks:
    - name: Copy IOS XE image via TFTP
      cisco.ios.ios_command:
        commands:
          - "copy tftp://{{ tftp_server }}/{{ new_file }} flash:/{{ new_file }}"
        wait_for:
          - "Address or name of remote host []?"
          - "Source filename []?"
          - "Destination filename [{{ new_file }}]?"

    - name: Save Configuration
      cisco.ios.ios_command:
        commands:
          - "write memory"
