---
- name: Copy IOS XE image to switch
  hosts: all  # Specify the target hosts here
  gather_facts: no
  vars:
    tftp_server: 10.1.196.117  # TFTP server IP address
    ios_image_filename: cat9k_lite_iosxe.17.09.03.SPA.bin  # The name of the IOS XE image file

  tasks:
    - name: Copy IOS XE image via TFTP
      ios_command_string:
        commands:
          - "copy tftp://{{ tftp_server }}/{{ ios_image_filename }} flash:/{{ ios_image_filename }}"
          - "Address or name of remote host []?"
          - "{{ tftp_server }}"
          - "Source filename []?"
          - "{{ ios_image_filename }}"
          - "Destination filename [{{ ios_image_filename }}]?"
