---
- name: Gather Cisco Router and Switch Inventory
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Collect Cisco facts
      ansible.builtin.ios_facts:
      register: cisco_facts

- name: Check IOS version and Copy image if needed
  hosts: cisco_devices
  gather_facts: no
  connection: network_cli
  vars:
    new_ios_image: "cisco_ios_15.2.7E7.bin"  # The name of the new IOS image file.
    desired_version: "15.2(7)E7"            # The desired IOS version for the upgrade.

  tasks:
    - name: Check current IOS version
      set_fact:
        current_version: "{{ cisco_facts.ansible_facts.net_version }}"

    - name: Compare current version with desired version
      when: current_version != desired_version
      block:
        - name: Copy new IOS image to device
          ios_command:
            commands:
              - "copy tftp://{{ ansible_host }}/{{ new_ios_image }} flash:/{{ new_ios_image }}"
              - "verify /md5 flash:/{{ new_ios_image }}"
          register: copy_result

        - name: Compare MD5 hashes
          assert:
            that:
              - copy_result.stdout_lines[-2] | regex_search('.*OK.*')
            msg: "MD5 mismatch. The copied file is corrupted."

      when: current_version != desired_version
