---
- name: Switch Reload
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Gather facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output

    - name: print output
      debug:
        msg: "Current Version is {{ facts_output['ansible_facts']['ansible_net_version'] }}"

    - name: Save the Config
      cisco.ios.ios_command:
        commands:
          - command: 'copy running-config startup-config'
            prompt: 'Destination filename \[startup-config\]\?'
            answer: "\r"
      register: save_config

    - name: Save config output
      debug:
        msg: "{{ save_config }}"

    - name: Reload the Device
      cli_command:
        command: reload
        prompt:
          - confirm
        answer:
          - 'y'

    - name: Wait for switch to reboot and become reachable
      wait_for_connection:
        delay: 180
        sleep: 60
        timeout: 900

    - name: Gather new facts
      cisco.ios.ios_facts:
        gather_subset: hardware
      register: facts_output_new
