---
- name: Reboot Cisco Switches
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot the Cisco switch
      ios_command:
        commands:
          - reload

    - name: Wait for the switch to reboot
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        state: started
        delay: 30
        timeout: 600

    - name: Verify switch version
      ios_facts:
        gather_subset: hardware
      register: switch_facts

    - name: Print switch version
      debug:
        var: switch_facts.ansible_net_version
