---
- name: Reboot Cisco Switches
  hosts: all
  gather_facts: no

  tasks:
    - name: Reboot the Cisco switch
      ios_command:
        commands:
          - reload
        wait_for: rebooted
        wait_for_timeout: 600
      register: reboot_result

    - name: Print reboot result
      debug:
        var: reboot_result
