- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: run sh ver to get model name and serial number
      ios_command:
        commands:
          - show version | include Model
          - show version | include Serial Number
      register: sh_ver_result

    - name: Extract model name and serial number
      set_fact:
        model_name: "{{ sh_ver_result.stdout_lines | select('search', 'Model') | first | regex_find('Model\\s+(\\S+)') }}"
        serial_number: "{{ sh_ver_result.stdout_lines | select('search', 'Serial Number') | first | regex_find('Serial Number\\s+(\\S+)') }}"

    - name: Debug model name and serial number
      debug:
        msg: "Model Name: {{ model_name }}, Serial Number: {{ serial_number }}"
