---
- name: Define Parameters
  hosts: hosts
  gather_facts: no
  connection: network_cli
  
  tasks:
  - name: Get the facts
    ios_facts:
      gather_subset: all
  - name: Display model and serial number
    debug :
    msg: "model number of {{ ansible_net_hostname }} is {{ ansible_net_model }} is {{ ansible_net_seiralnum}}"
