- name: Gather Cisco Router and Switch Inventory
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Collect Cisco facts
      ios_facts:
      register: cisco_facts

    - name: Display Cisco inventory
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model Name: {{ cisco_facts.model }}
          Serial Number: {{ cisco_facts.serialnum }}
          Hostname: {{ cisco_facts.hostname }}
          IOS Version: {{ cisco_facts.version }}
          Interfaces: {{ cisco_facts.interfaces | json_query('[*].interface') | join(', ') }}
