- name: Gather Cisco Router and Switch Inventory
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Collect Cisco facts
      ios_facts:
      register: cisco_facts

    - name: Display Cisco inventory
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model Name: {{ cisco_facts.ansible_facts.model | default('N/A') }}
          Serial Number: {{ cisco_facts.ansible_facts.serialnum | default('N/A') }}
          Hostname: {{ cisco_facts.ansible_facts.hostname | default('N/A') }}
          IOS Version: {{ cisco_facts.ansible_facts.version | default('N/A') }}
          Interfaces: {{ cisco_facts.ansible_facts.interfaces | default([]) | json_query('[*].interface') | join(', ') }}
