- name: Initial Playbook
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: run sh ver to get model name and serial number
      ios_command:
        commands:
          - show version | include Model
          - show version | include Serial Number
      register: sh_ver_result

    - name: Extract model name and serial number
      set_fact:
        model_name: "{{ sh_ver_result.stdout | regex_search('Model\\s+(\\S+)') | trim }}"
        serial_number: "{{ sh_ver_result.stdout | regex_search('Serial Number\\s+(\\S+)') | trim }}"

    - name: Debug model name and serial number
      debug:
        msg: "Model Name: {{ model_name }}, Serial Number: {{ serial_number }}"
