- name: Gather Cisco Router and Switch Inventory
  hosts: all
  gather_facts: no
  connection: network_cli
  tasks:
    - name: Collect Cisco facts
      ansible.builtin.ios_facts:
      register: cisco_facts

    - name: Display Cisco inventory
      debug:
        msg: |
          Device: {{ inventory_hostname }}
          Model Name: {{ cisco_facts.ansible_facts.ansible_net_model | default('N/A') }}
          Serial Number: {{ cisco_facts.ansible_facts.ansible_net_serialnum | default('N/A') }}
          Hostname: {{ cisco_facts.ansible_facts.ansible_net_hostname | default('N/A') }}
          IOS Version: {{ cisco_facts.ansible_facts.ansible_net_version | default([]) | join(', ') }}
